/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tag": {
    "Javascript": {
      "key": "Javascript",
      "scope": "tag",
      "path": "/tag/Javascript/",
      "pageKeys": [
        "v-f17081e2",
        "v-42f43eae",
        "v-7b707e42",
        "v-5dd18d09",
        "v-06774269"
      ]
    },
    "业务": {
      "key": "业务",
      "scope": "tag",
      "path": "/tag/业务/",
      "pageKeys": [
        "v-7cbf6b2e"
      ]
    },
    "设计模式": {
      "key": "设计模式",
      "scope": "tag",
      "path": "/tag/设计模式/",
      "pageKeys": [
        "v-5dd18d09"
      ]
    },
    "工具": {
      "key": "工具",
      "scope": "tag",
      "path": "/tag/工具/",
      "pageKeys": [
        "v-06774269",
        "v-dcfe636e"
      ]
    },
    "Webpack": {
      "key": "Webpack",
      "scope": "tag",
      "path": "/tag/Webpack/",
      "pageKeys": [
        "v-dcfe636e"
      ]
    }
  }
}