/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tag": {
    "Javascript": {
      "key": "Javascript",
      "scope": "tag",
      "path": "/tag/Javascript/",
      "pageKeys": [
        "v-00ddcb3c",
        "v-3ee8e8a8",
        "v-48e6157c",
        "v-5fbca62e",
        "v-0831abac"
      ]
    },
    "业务": {
      "key": "业务",
      "scope": "tag",
      "path": "/tag/业务/",
      "pageKeys": [
        "v-2b18b14c"
      ]
    },
    "3D图形": {
      "key": "3D图形",
      "scope": "tag",
      "path": "/tag/3D图形/",
      "pageKeys": [
        "v-17d2a884",
        "v-92bbf354"
      ]
    },
    "设计模式": {
      "key": "设计模式",
      "scope": "tag",
      "path": "/tag/设计模式/",
      "pageKeys": [
        "v-5fbca62e"
      ]
    },
    "Webpack": {
      "key": "Webpack",
      "scope": "tag",
      "path": "/tag/Webpack/",
      "pageKeys": [
        "v-689ea80a"
      ]
    },
    "工具": {
      "key": "工具",
      "scope": "tag",
      "path": "/tag/工具/",
      "pageKeys": [
        "v-689ea80a",
        "v-0831abac"
      ]
    }
  }
}